version: "3.2"

services:
  mariadb:
    build:
      context: ./
      args:
        MARIADB_VERSION: $MARIADB_VERSION
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root0!
      MYSQL_DATABASE: agramar
      MYSQL_USER: agramar
      MYSQL_PASSWORD: agramar0!
      TZ: Asia/Seoul
    networks:
      - backend

networks:
  backend:
    driver: bridge
